### ISSUE TITLE
Not working for me in latest version of Safari

### ISSUE THREAD

**Issue by k3mist** [350d/stylish#7] opened 2015-05-28 21:14 UTC
All of my styles are gone and I can not create or install new ones. Also there appears to be an HTML element inserted incorrectly into the UI.

Not sure what is going on, I've tried to deleting and reinstalling the extension. 

FYI: I recently restored my laptop, not sure if there is something else I could be looking for, like a permissions issue maybe?

Stylish Version 1.6 

![screen shot 2015-05-28 at 2 11 18 pm](https://cloud.githubusercontent.com/assets/439440/7871242/81938a22-0543-11e5-90d1-a4ceefafb9f0.png)

![screen shot 2015-05-28 at 2 18 11 pm](https://cloud.githubusercontent.com/assets/439440/7871409/847db8a6-0544-11e5-82a2-9c1cb62a0e6a.png)

**Comment by 350d** [comment] 2015-05-28 21:21
Can check the console for errors?

**Comment by k3mist** [comment] 2015-05-28 21:25
Ghostery is blocking the links to social media. Are those blocking functionality?

![screen shot 2015-05-28 at 2 24 22 pm](https://cloud.githubusercontent.com/assets/439440/7871550/6dcc8d16-0545-11e5-981a-d2c835b89540.png)

**Comment by k3mist** [comment] 2015-05-28 21:28
![screen shot 2015-05-28 at 2 28 19 pm](https://cloud.githubusercontent.com/assets/439440/7871610/d7568818-0545-11e5-87c1-dbd413188474.png)

**Comment by k3mist** [comment] 2015-05-28 21:31
Disabled ghostery, same two errors;

![screen shot 2015-05-28 at 2 31 39 pm](https://cloud.githubusercontent.com/assets/439440/7871677/4aa5e5d4-0546-11e5-8e2b-7b36fa938231.png)

**Comment by 350d** [comment] 2015-05-28 21:32
Looks like you don't have a info.plist file in extension folder

**Comment by k3mist** [comment] 2015-05-28 21:35
Yeah, any ideas how to fix?

Is it a problem with my safari or extension?

**Comment by 350d** [comment] 2015-05-28 21:35
Problem on your end, this file should be there after install.

**Comment by k3mist** [comment] 2015-05-28 21:39
I deleted ~/Library/Safari, installed stylish, still not working.

Do you know what else could cause this?

**Comment by 350d** [comment] 2015-05-28 21:43
Check the extension folder for info.plist and if it exist - repair permission.

**Comment by k3mist** [comment] 2015-05-28 21:50
This folder? 

![screen shot 2015-05-28 at 2 48 05 pm](https://cloud.githubusercontent.com/assets/439440/7871970/ce62bae4-0548-11e5-807b-ea1db86a8800.png)

**Comment by 350d** [comment] 2015-05-28 21:51
Yes, copy Stylish.* to desktop and rename it to *.zip and unpack. If you can find the info.plist - everything is ok with extension file and problem is on your local computer.

**Comment by k3mist** [comment] 2015-05-28 21:59
Rename to zip not working. 

Stylish.safariextz.zip > Stylish.safariextz.zip.cpgz > Stylish.safariextz 2.zip > Stylish.safariextz 2.zip.cpgz

![screen shot 2015-05-28 at 2 59 05 pm](https://cloud.githubusercontent.com/assets/439440/7872099/1e28426e-054a-11e5-809e-f078a9c59f37.png)

**Comment by 350d** [comment] 2015-05-28 22:57
You need to change .safariextz to .zip

**Comment by k3mist** [comment] 2015-05-30 00:22
I did that, it unzips to a .cpgz which unzips to a .zip. The cycle is never ending.

**Comment by 350d** [comment] 2015-05-30 01:11
Following your screenshot - you doing it in wrong way. Anyway, nothing about extension, the problem is on your computer. I don't have similar reports from very beginning of the development, so, i'm closing this report.

**Comment by frankdugan3** [comment] 2015-12-04 13:23
I have the same exact issue. I disabled all extensions, reinstalled several times from both the website and the Apple extension library. I had the same issue when unzipping, but I went ahead and used Unarchiver instead, and the Info.plist was in there. I'm not sure what permissions it needed, but Everyone had read and my user was read+write. 

Also, when first opening by clicking on "Find more," there are two other files that can't be found:
![console](https://cloud.githubusercontent.com/assets/10977914/11590633/7e8fed0a-9a5f-11e5-85e8-2c4e3edeaf78.png)

When I reload "Find more" by navigating back and forth from other sections, those two errors disappear. I suspect there may be an issue with how files are linking.

While the issue may be related to my particular setup, I don't see how I am doing anything wrong. While we may be the only two reporters, there could be other people experiencing this that just haven't bothered. Any further suggestions?

**Comment by 350d** [comment] 2016-01-09 03:15
@k3mist, @frankdugan3  guys, looks like you have similar setup issues, something like proxy, firewall settings or third party blocking apps, can you communicate here and find possible stop factors? Thank you!

**Comment by frankdugan3** [comment] 2016-01-09 03:50
No proxy, firewall off, no other plugins installed, cache and history cleared, default settings restored. Whatever the issue, it affects Safari in its factory state.

I just tried again and it worked for me with Safari 9.0.2. I don't recall which version was running when this issue occurred, but it seems to be resolved now.

**Closed** 2016-01-13 20:34 UTC

**Comment by 350d** [comment] 2016-02-11 15:35
Possible related to your case - https://github.com/350d/stylish/issues/12

**Comment by ghost** [comment] 2018-08-11 21:54
I had the same problem and I just solved it a few seconds ago by clicking on the stylish logo and then "manage" to edit the currently selected user style. All I had to do now was check for updates for this style and (surprise) there was a new version available. So I simply hit the "update" button and within like 1 second the style was updated and after reloading youtube once everything worked fine again.

**Comment by k3mist** [comment] 2018-08-23 18:29
@frankdugan3 are you using case-sensitive journal? This issue went away for me on non-case sensitive journal and I believe it may be the cause. If you're on case-sensitive it would confirm.

@350d this might be the cause ^

**Comment by frankdugan3** [comment] 2018-08-23 18:34
@k3mist  Not sure, I don't use this plugin anymore.

**Comment by k3mist** [comment] 2018-08-23 19:02
@frankdugan3 Are you still using OSX? To find out would be from Terminal

`diskutil info /`

Relevant part is;

```   
File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)
```

**Comment by frankdugan3** [comment] 2018-08-23 19:08
@k3mist I'm using `apfs`, not `hfs`.

**Comment by k3mist** [comment] 2018-08-24 16:22
@frankdugan3 apfs and hfs both support case-insensitive and case-sensitive file system types and i think it might be the cause of this weird bug i reported way back, which is why I asked. no big deal if you don't want to share the output.

**Comment by frankdugan3** [comment] 2018-08-25 13:54
Sorry, wasn't trying to be evasive, just concise.
```
File System Personality:  APFS
Type (Bundle):            apfs
Name (User Visible):      APFS
```

That said, way back when I reported that I had the issue too, I was using case-sensitive `hfs`.
